# Generated by Django 5.0.6 on 2024-07-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_connections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='field_of_expertise',
            new_name='field_of_experties',
        ),
    ]
