# Generated by Django 5.0.6 on 2024-07-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_field_of_expertise_useraccount_field_of_experties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='field_of_experties',
            new_name='field_of_expertise',
        ),
    ]
